### PR TITLE
Docker configuration for the "full" example app

### PR DESCRIPTION
**Pull request by MikiDi**
My first motivation for doing this was to be able to test the project myself :man_shrugging: . It's more than it looks like for someone who isn't used to configuring apache/php-setups :nerd_face: . Among [other advantages](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.0_release_notes/sect-red_hat_enterprise_linux-7.0_release_notes-linux_containers_with_docker_format-advantages_of_using_docker) the Docker approach (drastically) lowers the setup time, lowering the bar for new contributors.

Only configured the `full` example for now. Once everyone agrees on this PR, I could easily add config for the others.

Some things worth noting:
- As noted in https://github.com/openwanderer/server/pull/1#issue-619671617 , the used postgis docker image doesn't support no-password-setup of the DB. Therefore I had to add the password config to the server-repo. This is the only thing I had to change wrt the native setup. Apart from that, this docker setup should work exactly the same as the native one.  
- Switched the used version of the `openwanderer/openwanderer` composer dependency to the untagged `dev-master`. This to be able to demonstrate this is working, since these last changes are required for the docker setup.
- For the docker setup, I configured the folder for sharing panorama's to `/var/www/html/panoramas`, since `/var/www/html/panos` somehow conflicted with the `panos` endpoint of the php server. When trying to fetch a request on the php endpoint, apache tried to list the contents of the `panos` folder instead (and failed because no dir listing permission). Don't think this is related to the docker deployment though?

### CODE REVIEW

**Comment by nickw1** [comment]
@MikiDi many, many thanks for this, it will be *really* useful for lowering the bar to entry :-) I will test it over the weekend and then merge if all is well. @mrAceT any comments?

For your third point, re. the `/var/www/html/panos` directory, the intention is that the panos should be uploaded to a publicly-inaccessible directory as it will allow users to view unmoderated panos, or panos which haven't yet passed through the face and license plate filter (WIP). On my test system on my laptop, I do use `/var/www/html/panos` for convenience, but on my public server I use a private directory. But yes, no harm in renaming it to `panoramas`.

**Comment by mrAceT** [comment]
looks great!

**Comment by nickw1** [comment]
@MikiDi OK have tested, works fine. Just a thought before I merge: I changed the port to something other than 80 (8888) as I already have an Apache server running on my system. Do we want to do this so that the Docker app can be accessed independently of the host machine's Apache server?

**Comment by nickw1** [comment]
@MikiDi OK have merged, and updated the port in `docker-compose.yml`, so feel free to do the other example apps whenever you are able :-)

**Comment by MikiDi** [comment]
Allright! :ok_hand:

**Pull request merged**
